# Generated by Django 5.1.2 on 2024-10-12 09:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=20, verbose_name='firstName')),
                ('last_name', models.CharField(max_length=20, verbose_name='lastName')),
                ('username', models.CharField(max_length=20, verbose_name='username')),
                ('profile', models.ImageField(blank=True, default='profiles/default.jpg', upload_to='profiles/', verbose_name='profilePic')),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=25, verbose_name='To')),
                ('start', models.CharField(max_length=25, verbose_name='From')),
                ('travel_date', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('isComplete', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
        ),
    ]
