# Generated by Django 5.1.2 on 2024-11-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_travel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='client',
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='client', max_length=25),
        ),
    ]
