# Generated by Django 5.1.2 on 2024-10-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_customuser_is_active_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='destination',
            new_name='destination_city',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='start',
            new_name='starting_city',
        ),
    ]
