# Generated by Django 5.1.2 on 2024-11-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_booking_client_booking_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='email', max_length=30, verbose_name='email'),
        ),
    ]
